CREATE DATABASE sir;

CREATE TABLE sir.education(
    state VARCHAR(20) PRIMARY KEY UNIQUE NOT NULL,
    abbreviation CHAR(2) NOT NULL,
    population_2018 INT,
    population_2020 INT,
    population_2021 INT,
    growth_2021 DECIMAL(3,2),
    census_2010 INT,
    growth_since_2010 INT,
    percent_of_us DECIMAL(3,2),
    density int,
    graduation_rate DECIMAL(3,1),
    instruction_spending_per_pupil FLOAT,
    support_spending_per_pupil FLOAT,
    total_spending_per_pupil FLOAT,
    total_instruction_spending INT,
    total_spending INT,
    total_support_spending INT,
    black_population INT,
    hispanic_population INT,
    native_american_population INT,
    asian_population INT,
    pacific_islander_population INT,
    white_population INT,
    other_population INT,
    african_american_percent DECIMAL(4,2),
    percent_victims_black INT,
    disparity INT,
    black_people_killed INT,
    hispanic_people_killed INT,
    native_american_people_killed INT,
    asian_people_killed INT,
    pacific_islanders_killed INT,
    white_people_killed INT,
    unknown_race_killed INT,
    black_death_rate DECIMAL(4,2),
    hispanic_death_rate DECIMAL(4,2),
    native_american_death_rate DECIMAL(4,2),
    asian_death_rate DECIMAL(4,2),
    pacific_islanders_death_rate DECIMAL(4,2),
    white_death_rate DECIMAL(4,2),
    all_people_rate DECIMAL(4,2),
    disparity_in_rate DECIMAL(3,2),
    black_white_disparity DECIMAL(4,2),
    hispanic_white_disparity DECIMAL(3,2),
    native_american_white_disparity DEC(4,2)
);